Refactor capítulos dos Livros Digitáis e páginas dos Sites
practice-uffs/maker pull request #51
Opened 2021-10-13 04:29 UTC by GuilhermeGraeff

Agora o livro digital suporta estruturas do tipo:
![image](https://user-images.githubusercontent.com/48657331/137066420-0c663e82-4a5b-4c7d-9a08-c1cf3d9856de.png)

<hr>

A ferramenta que gera a estrutura inicial de diretórios para as páginas dos sites suporta algo do tipo: 
![image](https://user-images.githubusercontent.com/48657331/137067005-2e936fa5-c52d-4a4e-aee1-744c48952589.png)
![image](https://user-images.githubusercontent.com/48657331/137067233-e3e212e2-54e3-44ca-acf8-e0aa4a30f6ff.png)

fix: #49

2021-10-13 12:15 UTC, Dovyski requested changes
Fiz alguns comentários sobre melhoras na estrutura e segurança. De resto está ótimo!

2021-10-13 12:15 UTC, Dovyski commented on app/Jobs/MakeSiteJob.php
> +            exec('rm -r '. $absolutePathToFolder .'*');
Isso é muito perigoso de ser feito. Não podemos usar essa implementação. A classe `Storage` do Laravel não tem algum método para apagar pastas recursivamente (que é o mesmo que usar `rm -r`)?.

2021-10-13 12:15 UTC, Dovyski commented on app/Jobs/MakeSiteJob.php
> +                    Storage::disk('sites')->put("$folder/$path/index.html", $fileContent);
Eu acho que essa linha (que é muito parecida com a que tem no `else` poderia ser removida do `if` e do `else` e colocada depois. Algo do tipo:

```php
$path = $folder;

if (  ) {
    $path .= '/...';
} else {
    $path .= '/.../../.../';
}

Storage::disk('sites')->put("$path/index.html", $fileContent);
```

Eu acho que isso deixaria o código com menos chance de problemas no futuro.

2021-10-13 12:15 UTC, Dovyski commented on app/Jobs/MakeSiteJob.php
> +                    Storage::disk('sites')->put("$folder/$path/index.html", $fileContent);
Eu acho que essa linha (que é muito parecida com a que tem no `else` poderia ser removida do `if` e do `else` e colocada depois. Algo do tipo:

```php
$path = $folder;

if (  ) {
    $path .= '/...';
} else {
    $path .= '/.../../.../';
}

Storage::disk('sites')->put("$path/index.html", $fileContent);
```

Eu acho que isso deixaria o código com menos chance de problemas no futuro.

2021-10-13 12:15 UTC, Dovyski commented on app/Jobs/UpdateSiteJob.php
> +        exec('rm -r '. $absolutePathToFolder .'*');
Precisamos remover isso, é muito perigoso. Dá uma olhada na classe `Storage` do Laravel para usar algum método que faça remoção recursiva de pastas.

2021-10-13 12:15 UTC, Dovyski commented on app/Jobs/UpdateSiteJob.php
>          $updatedSite->build_output = 'Done';
Acho que essa linha foi duplicada sem querer.

2021-10-13 12:15 UTC, Dovyski commented on app/Jobs/UpdateSiteJob.php
> +                Storage::disk('sites')->put("$folder/$path/index.html", $fileContent);
Eu acho que essa linha (que é muito parecida com a que tem no `else` poderia ser removida do `if` e do `else` e colocada depois. Algo do tipo:

```php
$path = $folder;

if (  ) {
    $path .= '/...';
} else {
    $path .= '/.../../.../';
}

Storage::disk('sites')->put("$path/index.html", $fileContent);
```

Eu acho que isso deixaria o código com menos chance de problemas no futuro.

2021-10-13 12:15 UTC, Dovyski commented on app/Services/GoogleDoc.php
> +                    array_push($siteContent, array( "path" => $outputPath[1],
Essa linha toda por ser simplificada (e fica mais fácil de ler) como:

```
$siteContent[] = [ "path" => $outputPath[1], "content" => ""],
```

2021-10-13 12:15 UTC, Dovyski commented on app/Services/GoogleDoc.php
> +            while ($hasLines){
Esse bloco todo de código é igual ao que existe mais para cima. Ele pode ser refatorado em um método separado.

2021-10-13 12:15 UTC, Dovyski commented on app/Services/GoogleDoc.php
> +            $bookContent = array();
Esse bloco todo pode ser escrito de uma forma melhor (e mais fácil de ler):

```php

$bookContent = [
    [
         'title' => "Capítulo não informado\r\n",
         'content' => '',
         'chapter' => 0,
   ]
];
```

2021-10-13 12:15 UTC, Dovyski commented on app/Services/GoogleDoc.php
> +                if($content == "" & $title == "Capítulo não informado\r\n"){
```suggestion
                if($content == "" && $title == "Capítulo não informado\r\n"){
```

2021-10-13 12:15 UTC, Dovyski commented on app/Services/GoogleDoc.php
> +            while ($hasLines){
Refatorar esse bloco de código em um método próprio.

2021-10-13 12:15 UTC, Dovyski commented on app/Services/GoogleDoc.php
> +                    file_put_contents("book/content/$fileName.md",$content);
Esse código não colocará o conteúdo de *todos* os livros sendo gerados por diferentes usuários no mesmo local? Se esse for o caso, precisamos criar uma issue para arrumar isso. A solução é relativamente fácil, podemos colocar o id do livro no path do caminho, tipo `book/$id/content/...`.

2021-10-14 11:37 UTC, GuilhermeGraeff commented on app/Services/GoogleDoc.php
> +                    file_put_contents("book/content/$fileName.md",$content);
Esse código gera os markdowns na pasta que ibis utiliza para gerar o pdf, então logo depois que o pdf é gerado os markdowns serão excluídos para que outro livro possa ser gerado.

2021-10-14 11:59 UTC, Dovyski commented
E se houver dois jobs trabalhando ao mesmo tempo, eles vão usar essa mesma
pasta, certo?

2021-10-14 12:25 UTC, GuilhermeGraeff commented on app/Jobs/MakeSiteJob.php
> +            exec('rm -r '. $absolutePathToFolder .'*');
Storage::disk('sites')->deleteDirectory($folder);

Encontrei isso, faz a mesma função de excluir para poder gerar um novo.

2021-10-14 12:41 UTC, GuilhermeGraeff commented on app/Jobs/MakeSiteJob.php
> +                    Storage::disk('sites')->put("$folder/$path/index.html", $fileContent);
Ficou assim após a alteração:
```
foreach ($this->site->contents as $content){
    $path = $content['path'];
    if( $path != 'caminho-nao-informado'){
        $path = str_replace('/','nova-contra-barra',$path);
        $path = Str::slug($path);
        $path = str_replace('nova-contra-barra','/',$path);
        $path = "$folder/$path/index.html";
    } else {
        path = "$folder/index.html";
    }
    Storage::disk('sites')->put($path, $content['content']);
}
```

2021-10-14 12:43 UTC, GuilhermeGraeff commented on app/Jobs/MakeSiteJob.php
> +                    Storage::disk('sites')->put("$folder/$path/index.html", $fileContent);
Mesma coisa da outra:
```
foreach ($this->site->contents as $content){
    $path = $content['path'];
    if( $path != 'caminho-nao-informado'){
        $path = str_replace('/','nova-contra-barra',$path);
        $path = Str::slug($path);
        $path = str_replace('nova-contra-barra','/',$path);
        $path = "$folder/$path/index.html";
    } else {
        path = "$folder/index.html";
    }
    Storage::disk('sites')->put($path, $content['content']);
}
```

2021-10-14 12:45 UTC, GuilhermeGraeff commented on app/Jobs/UpdateSiteJob.php
> +        exec('rm -r '. $absolutePathToFolder .'*');
Storage::disk('sites')->deleteDirectory($folder);

Consegui achar essa função aplicada do 'disk' que eu to usando.

2021-10-14 12:48 UTC, GuilhermeGraeff commented on app/Jobs/UpdateSiteJob.php
>          $updatedSite->build_output = 'Done';
Não sei se eu entendi o comentário direito

Se for do "$updatedSite->build_status" e do "$updatedSite->build_output", é que diferente do Ibis que gera uma saída de "Livro gerado" no cmd, o site não é gerado de verdade ainda por uma ferramenta, então não tem saída para colocar no "build_output", também é uma opção deixar vazio.

2021-10-14 12:52 UTC, GuilhermeGraeff commented on app/Jobs/UpdateSiteJob.php
> +                Storage::disk('sites')->put("$folder/$path/index.html", $fileContent);
Resolvido, semelhante aos outro casos que também foram resolvidos.

2021-10-14 12:57 UTC, GuilhermeGraeff commented on app/Services/GoogleDoc.php
> +                    array_push($siteContent, array( "path" => $outputPath[1],
Certo, substituí e funcionou :)

2021-10-14 13:08 UTC, GuilhermeGraeff commented on app/Services/GoogleDoc.php
> +            while ($hasLines){
Criei uma função chamada parseDocsToArray() e encapsulei esta operação, pode ser utilizada futuramente por outras funções para transformar um Google Docs em um array que cada posição é uma linha do docs.

2021-10-14 13:14 UTC, GuilhermeGraeff commented on app/Services/GoogleDoc.php
> +            $bookContent = array();
Foi substituído, fica bem mais legível mesmo :) :+1:

2021-10-14 13:15 UTC, GuilhermeGraeff commented on app/Services/GoogleDoc.php
> +                if($content == "" & $title == "Capítulo não informado\r\n"){
Resolvido

2021-10-14 13:16 UTC, GuilhermeGraeff commented on app/Services/GoogleDoc.php
> +            while ($hasLines){
Refatorado em "parseDocsToArray()", pode ser reutilizado futuramente uhul

2021-10-14 13:17 UTC, GuilhermeGraeff commented
Sim, para gerar o livro digital, os markdowns utilizam a mesma pasta.

2021-10-14 13:22 UTC, GuilhermeGraeff commented on app/Services/GoogleDoc.php
> +            $bookContent = array();
Seguindo a mesma ideia eu ainda vou trocar 
```
array_push($bookContent, array( "title" => preg_replace('/{(.*)}/', '', $line),
                                                        "content" => "",
                                                        "chapter" => $chapter));
```
por 
```
$bookContent[] = [ 
          "title" => $outputPath[1], 
          "content" => "",
          "chapter" => $chapter
]
```

2021-10-14 13:43 UTC, GuilhermeGraeff commented
Eu não sei se é recessário requisitar um novo review, cliquei ali para ver o que aconteceria e solicitei um novo review heheheh

2021-10-14 20:25 UTC, Dovyski commented on app/Services/GoogleDoc.php
> +            }
Eu acho que esse bloco todo de `foreach() { ... }` pode ser abstraído em um método que recebe `$arrayOfLines` e retorna um `$bookContent` (inclusive o bloco `$bookContent = [ ... ]` que tem logo acima poderia ficar dentro da função também).

2021-10-14 20:25 UTC, Dovyski approved these changes
Em termos do review que eu fiz, está ótimo, obrigado! Eu fiz um comentário para deixar o código ainda mais legível, mas fica a teu critério ajustar ou não.

2021-10-15 11:48 UTC, GuilhermeGraeff commented on app/Services/GoogleDoc.php
> +            }
Feito o brique, aproveitei e fiz a mesma coisa no site também que faz algo parecido :) :+1:

2021-10-15 11:49 UTC, Dovyski approved these changes
Não ficou uma lindeza agora? 😄 Obrigado! ❤️

2021-10-18 23:43 UTC, CleissonVieira approved these changes

2021-10-19 00:01 UTC, merged