Feat: Alterado o ícone do maker no maker
practice-uffs/maker pull request #59
Opened 2022-03-04 18:36 UTC by GuilhermeGraeff

Foi adicionado o ícone no Maker, ficou maravilhoso, seguem os prints:

![image](https://user-images.githubusercontent.com/48657331/156819779-7b7d3176-e1cb-4de5-9c3d-bb0bbf9ce940.png)

![image](https://user-images.githubusercontent.com/48657331/156819796-37aaa107-5efa-4185-b286-403218f06c47.png)

![image](https://user-images.githubusercontent.com/48657331/156819848-d5658a07-9017-41f5-a16a-ed12e872f1ef.png)

Fix: #58

2022-03-07 11:04 UTC, alissonpeloso commented
@GuilhermeGraeff, uma coisa que dá pra arrumar é no modo `mobile`.

Se você tá no modo mobile e tentar entrar, você não achar o botão para login. Acredito que não seja muito complicado.

Se quiser pode abrir nova tarefa pra isso, ou fazer nessa mesmo

2022-03-07 11:05 UTC, alissonpeloso requested changes
Só ajusta o botão de login no mobile

2022-03-07 11:08 UTC, GuilhermeGraeff commented
Vou arrumar nessa mesmo :)

2022-03-07 11:44 UTC, GuilhermeGraeff commented
Dexei assim:

![aaaaaaaaaaaaaaaaaaaaaaaaaaasdsdsdsddddddddddddddddddddd](https://user-images.githubusercontent.com/48657331/157027954-54fe0418-94a4-40f7-86cd-e1aaa8c49a59.gif)

2022-03-07 11:52 UTC, alissonpeloso requested changes
Ele fica sem botão de login aqui:

![image](https://user-images.githubusercontent.com/51202705/157029411-bce4021a-2cb5-4769-a941-9d236ebd1bd0.png)

se tu entra no aplicativo pelo mobile, não consegue fazer nada

2022-03-08 12:00 UTC, GuilhermeGraeff commented
Puts, eu pensei que tu tava falando do botão 'entrar', que tu clica pra fazer o login, daí ajustei ele, não pensei que era o botão que ia pra tela de login.

Vou ajustar agora...

2022-03-08 12:14 UTC, GuilhermeGraeff commented
Ficou assim:

![ttttttttttt](https://user-images.githubusercontent.com/48657331/157235981-40c800a6-cb4d-424a-8044-04872b78fb4b.gif)

2022-03-08 12:59 UTC, alissonpeloso approved these changes

2022-03-08 12:59 UTC, merged