Melhorias UI/UX para gerar Livro Digital
practice-uffs/maker pull request #76
Opened 2022-05-31 06:00 UTC by CleissonVieira

Fix: #74 

Realizei ajustes nos fluxos de criar/listar/acessar Livro digital.
Melhorei o UI/UX na totalidade.
Ainda existem ajustes a serem feitos, vou continuar da issue #75 
Realizo o Merge para não impedir o @GuilhermeGraeff de dar continuidade em sua tarefa

2022-05-31 10:42 UTC, alissonpeloso requested changes
![image](https://user-images.githubusercontent.com/51202705/171154547-405c4c29-2c66-4ed0-a3a7-71690499bed3.png)

Acho que aqui ficaria melhor se removesse essa shadow aqui.

---

![image](https://user-images.githubusercontent.com/51202705/171155516-42d1a16a-81c0-48f7-9fbd-a525a2a08b8f.png)

Aqui ficou essa parte branca no lado direito quando a tela está cheia

2022-05-31 13:24 UTC, GuilhermeGraeff requested changes
É assim:

![image](https://user-images.githubusercontent.com/48657331/171179501-985c53ac-3e2c-4906-bbb1-ee07b8b5fc02.png)

![image](https://user-images.githubusercontent.com/48657331/171179595-cd36c376-dbb7-463e-89a5-8307e37b8e5f.png)


Acho que poderia ser feito como no print abaixo, acho que fica mais bonitinho, mas você que sabe também :)

![image](https://user-images.githubusercontent.com/48657331/171179196-30b11077-fbfd-47ca-8298-cb4e6ca38677.png)

![image](https://user-images.githubusercontent.com/48657331/171179131-1548150a-94d3-41a0-8185-301cd546ac14.png)


<hr />

O botão de criar livro invade o footer, talvez fosse lega fazer ele não invadir o footer, ou se invadir, não deixar que fique 'atrás' do conteúdo do footer

![image](https://user-images.githubusercontent.com/48657331/171180016-5f051980-4d04-4ef8-9fbd-58ec96cbf160.png)

A mesma coisa acontece na página dos livros, o botão invade o footer e fica 'atrás'.
![image](https://user-images.githubusercontent.com/48657331/171180370-ce81531d-fa2e-49ba-b964-babccbc6218a.png)

A mesma coisa acontece na página de um livro especifico, o botão invade o footer e fica 'atrás'.
![image](https://user-images.githubusercontent.com/48657331/171180767-bc21e49f-ab45-46eb-afd9-a1398e7e95f3.png)


No mais ficou bem legal :)

2022-06-01 00:12 UTC, CleissonVieira commented
> ![image](https://user-images.githubusercontent.com/51202705/171154547-405c4c29-2c66-4ed0-a3a7-71690499bed3.png)
> 
> Acho que aqui ficaria melhor se removesse essa shadow aqui.
> 
> ![image](https://user-images.githubusercontent.com/51202705/171155516-42d1a16a-81c0-48f7-9fbd-a525a2a08b8f.png)
> 
> Aqui ficou essa parte branca no lado direito quando a tela está cheia

Com sombra se refere a sombra na parte inferior ou ao background color da div?
Ajustei a responsividade, assim que ajustar a dica de todos informo para nova verificação.

2022-06-01 00:24 UTC, CleissonVieira commented
> É assim:
> 
> ![image](https://user-images.githubusercontent.com/48657331/171179501-985c53ac-3e2c-4906-bbb1-ee07b8b5fc02.png)
> 
> ![image](https://user-images.githubusercontent.com/48657331/171179595-cd36c376-dbb7-463e-89a5-8307e37b8e5f.png)
> 
> Acho que poderia ser feito como no print abaixo, acho que fica mais bonitinho, mas você que sabe também :)
> 
> ![image](https://user-images.githubusercontent.com/48657331/171179196-30b11077-fbfd-47ca-8298-cb4e6ca38677.png)
> 
> ![image](https://user-images.githubusercontent.com/48657331/171179131-1548150a-94d3-41a0-8185-301cd546ac14.png)
> 
> O botão de criar livro invade o footer, talvez fosse lega fazer ele não invadir o footer, ou se invadir, não deixar que fique 'atrás' do conteúdo do footer
> 
> ![image](https://user-images.githubusercontent.com/48657331/171180016-5f051980-4d04-4ef8-9fbd-58ec96cbf160.png)
> 
> A mesma coisa acontece na página dos livros, o botão invade o footer e fica 'atrás'. ![image](https://user-images.githubusercontent.com/48657331/171180370-ce81531d-fa2e-49ba-b964-babccbc6218a.png)
> 
> A mesma coisa acontece na página de um livro especifico, o botão invade o footer e fica 'atrás'. ![image](https://user-images.githubusercontent.com/48657331/171180767-bc21e49f-ab45-46eb-afd9-a1398e7e95f3.png)
> 
> No mais ficou bem legal :)

Segui a dica e deixei menor o aviso, conforme informou. Eu acho mais bonito usando todo o espaço hehehe
Sobre os botões flutuantes. Na tarefa #75 informei o ajuste para o footer, nessa tarefa irei ajustar esse bug dos itens sobrepondo.

2022-06-01 00:43 UTC, CleissonVieira commented
@alissonpeloso por gentileza, valida a informação sobre a sombra da resposta a seu comentário, se for aquilo está finalizado.

2022-06-01 10:42 UTC, alissonpeloso requested changes

2022-06-01 10:42 UTC, alissonpeloso commented on resources/views/livewire/make-book.blade.php
> +<div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-2 py-24">
```suggestion
<div class="bg-white overflow-hidden sm:rounded-lg px-2 py-24">
```

2022-06-01 10:42 UTC, alissonpeloso commented on resources/views/livewire/make-book.blade.php
> +<div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-2 py-24">
É essa sombra aqui @CleissonVieira

2022-06-01 12:21 UTC, CleissonVieira commented on resources/views/livewire/make-book.blade.php
> +<div class="bg-white overflow-hidden shadow-xl sm:rounded-lg px-2 py-24">
Perfeito, ajustei isso e adicionei novos ajustes de design:

- [x] Menu responsivo para celular (ex: criar menu lateral eliminando ferramentas para mobile)
- [x] Ajustar quando titulo do livro for maior que as div
- [x] Ajuste no design da listagem de livros

2022-06-01 12:22 UTC, CleissonVieira commented
Ajustei adicionais:

- [x] Menu responsivo para celular (ex: criar menu lateral eliminando ferramentas para mobile)
- [x] Ajustar quando titulo do livro for maior que as div
- [x] Ajuste no design da listagem de livros

2022-06-01 14:13 UTC, alissonpeloso commented
@CleissonVieira, acho que faltou adicionar as tags de @auth e @endauth no header, se vc está deslogado, ele dá erro pq não encontra o uid do usuário.

2022-06-01 16:03 UTC, CleissonVieira commented
@alissonpeloso perfeito, ajustei, não tinha notado esse detalhe

2022-06-01 21:43 UTC, merged