fix: ajustes footer #75
practice-uffs/maker pull request #77
Opened 2022-06-03 16:58 UTC by CleissonVieira

Fix: #75 

Ajustes onde botões flutuantes estavam sendo sobreposto por títulos e input do footer.
As div que deveriam ficar em linha estava ficando em coluna, ajustado também.

2022-06-06 11:23 UTC, alissonpeloso commented
O footer ficou assim pra mim, acho que poderia ficar igual do mural, desse jeito tá meio estranho
![image](https://user-images.githubusercontent.com/51202705/172151527-2659cb1c-1516-4c5c-8da3-e761bc6c1b7c.png)

2022-06-06 16:36 UTC, GuilhermeGraeff reviewed
Concordo com o que o @alissonpeloso mencionou, até pq já foi arrumado esse problema no mural né, se não me engano.

Gostaria de saber o motivo da remoção desse 'use' ali tmbm. 

![image](https://user-images.githubusercontent.com/48657331/172204560-d429e6a3-8abd-42d3-8600-dcded609e674.png)

2022-06-12 06:52 UTC, CleissonVieira commented
@GuilhermeGraeff Removi o use, pois, o VS Code indica que nunca é usado.

@alissonpeloso Ajustei o footer de acordo com Mural V2.
Porém realizei ajustes no input de NewsLetter, pois, usando relative e absolute acabava sobrepondo o botão flutuante, foi necessário remover e reajustar o CSS para isso não acontecer e ficar o mais próximo do antigo input

2022-06-13 10:41 UTC, alissonpeloso commented
Acho que teria que adicionar a tag de "Em construção" aqui também, na página inicial:

![image](https://user-images.githubusercontent.com/51202705/173336636-fe33798f-797b-4f0b-8202-bd802bcec39f.png)

2022-06-13 10:42 UTC, alissonpeloso requested changes

2022-06-13 10:42 UTC, alissonpeloso commented on resources/views/layouts/footer.blade.php
> +s
```suggestion

```

2022-06-14 10:23 UTC, alissonpeloso requested changes
Precisaria adicionar a tag "Em construção" na página inicial também:

![image](https://user-images.githubusercontent.com/51202705/173555732-3d261616-cc45-4f84-ae01-3b67aad2e184.png)

2022-06-14 10:49 UTC, CleissonVieira commented
@alissonpeloso sim eu já adicionei, aproveitei para desenvolver os loadings da issue #71 estou quase finalizando para o mesmo PR, ai pingo você para avaliar e dar merge com tudo junto

2022-06-14 12:44 UTC, CleissonVieira commented
Fix: #77 #71 

Adicionei loading conforme imagem abaixo. Desabilito o botão clicado, mudo de cor e trago a visão dos growing spinner no topo.
Implementei para botão de busca e criar livro.
Não encontrei uma forma de não precisar chamar uma div/span para cada growing ou utilizar os mesmos para ação de dois botões diferentes.

Dei merge com a dev.
@alissonpeloso liberado para code review

![image](https://user-images.githubusercontent.com/29258164/173577676-f0f24643-21ad-4542-882b-f117d3f8a2c2.png)

2022-06-14 12:55 UTC, merged